export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_SELECTED_RESULT = 'SET_SELECTED_RESULT';
export const FETCH_SEARCH_DATA_UNSUCCESSFUL = 'FETCH_SEARCH_DATA_UNSUCCESSFUL';
export const FETCH_REPO_INFO_BY_ID_UNSUCESSFUL = 'FETCH_REPO_INFO_BY_ID_UNSUCESSFUL';
